parameters:

services:
  orkestra.entity_manager:
    alias: doctrine.orm.entity_manager

  # Form types
  orkestra.type.enum:
    class: Orkestra\Bundle\ApplicationBundle\Form\EnumType
    tags:
      - { name: form.type, alias: enum }
  orkestra.type.phone:
    class: Orkestra\Bundle\ApplicationBundle\Form\PhoneType
    tags:
      - { name: form.type, alias: tel }
  orkestra.type.datetime:
    class: Orkestra\Bundle\ApplicationBundle\Form\DateTimeType
    tags:
      - { name: form.type, alias: datetime }
  orkestra.type.date:
    class: Orkestra\Bundle\ApplicationBundle\Form\DateType
    tags:
      - { name: form.type, alias: date }

  # Orkestra Common configuration
  orkestra.kernel.logger:
    class: Symfony\Bridge\Monolog\Logger
    arguments: [ orkestra.kernel ]
    calls:
      - [ pushHandler, [ @orkestra.kernel.logger.handler ] ]
  orkestra.kernel.logger.handler:
    class: Monolog\Handler\StreamHandler
    arguments: [ %kernel.root_dir%/logs/%kernel.environment%.kernel.log, 200 ]
  orkestra.kernel.http:
    class: Orkestra\Common\Kernel\HttpKernel
    arguments: [ @orkestra.kernel.logger ]
  orkestra.kernel.soap:
    class: Orkestra\Common\Kernel\SoapKernel
    arguments: [ @orkestra.kernel.logger ]

  # Helpers
  orkestra.mail_helper:
    class: Orkestra\Bundle\ApplicationBundle\Helper\MailHelper
    arguments: [ @templating, @twig ]
  orkestra.form_helper:
    class: Orkestra\Bundle\ApplicationBundle\Helper\FormHelper
    arguments: [ @service_container ]

  # Twig extensions
  orkestra.twig_extension:
    class: Orkestra\Bundle\ApplicationBundle\Twig\OrkestraExtension
    calls:
      - [ setContainer, [ @service_container ] ]
    tags:
      - { name: twig.extension }
