parameters:
  orkestra.worker_factory.class:            Orkestra\Bundle\ApplicationBundle\Worker\WorkerFactory
  orkestra.file_manager.base_path:          %kernel.root_dir%/files
  orkestra.ca_bundle.path:
  orkestra.system_email_address:

services:
  orkestra.entity_manager:
    alias: doctrine.orm.entity_manager
  orkestra.guzzle_client:
    class: Guzzle\Http\Client
    arguments:
      - ''
      - { 'curl.options': { 'CURLOPT_CAINFO': %orkestra.ca_bundle.path%, 'CURLOPT_SSL_VERIFYPEER': true } }

  # Form types
  orkestra.type.enum:
    class: Orkestra\Bundle\ApplicationBundle\Form\EnumType
    tags:
      - { name: form.type, alias: enum }
  orkestra.type.year:
    class: Orkestra\Bundle\ApplicationBundle\Form\YearType
    tags:
      - { name: form.type, alias: year }
  orkestra.type.phone:
    class: Orkestra\Bundle\ApplicationBundle\Form\PhoneType
    tags:
      - { name: form.type, alias: tel }
  orkestra.type.datetime:
    class: Orkestra\Bundle\ApplicationBundle\Form\DateTimeType
    tags:
      - { name: form.type, alias: datetime }
  orkestra.type.entity_choice:
    class: Orkestra\Bundle\ApplicationBundle\Form\EntityChoiceType
    arguments: [ @doctrine ]
    tags:
      - { name: form.type, alias: entity_choice }

  # Helpers
  orkestra.mail_helper:
    class: Orkestra\Bundle\ApplicationBundle\Helper\MailHelper
    arguments: [ @templating, @twig ]
  orkestra.form_helper:
    class: Orkestra\Bundle\ApplicationBundle\Helper\FormHelper
    arguments: [ @service_container ]

  orkestra.file_manager:
    class: Orkestra\Bundle\ApplicationBundle\Manager\FileManager
    arguments: [ %orkestra.file_manager.base_path% ]

  # Twig extensions
  orkestra.twig_extension:
    class: Orkestra\Bundle\ApplicationBundle\Twig\OrkestraExtension
    calls:
      - [ setContainer, [ @service_container ] ]
    tags:
      - { name: twig.extension }

  # Listeners
  orkestra.user_preferences_listener:
    class: Orkestra\Bundle\ApplicationBundle\Listener\UserPreferencesListener
    arguments: [ @service_container ]
    tags:
       - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  # Subscribers
  orkestra.subscriber.latitude_longitude:
    class: Orkestra\Bundle\ApplicationBundle\Subscriber\LatitudeLongitudeSubscriber
    tags:
      - { name: doctrine.event_subscriber }

  # Workers
  orkestra.worker_factory:
    class: %orkestra.worker_factory.class%
  orkestra.worker.latitude_longitude:
    class: Orkestra\Bundle\ApplicationBundle\Worker\LatitudeLongitudeWorker
    arguments: [ @orkestra.entity_manager, @orkestra.guzzle_client ]
    tags:
      - { name: orkestra.worker }
